version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: 
      context: ./check
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_USER=payment_user
      - DB_PASSWORD=payment_password
      - DB_NAME=payment_gateway
    ports:
      - "9001:9000"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=payment_gateway
      - MYSQL_USER=payment_user
      - MYSQL_PASSWORD=payment_password
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./check/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: